// Generated by CoffeeScript 1.10.0
(function($) {
  var menu, topbarIcon;
  topbarIcon = $('#topbar-icon');
  menu = $('.topbar-menu');
  return topbarIcon.on("click", function() {
    return menu.toggleClass("menu-activated");
  });
})(jQuery);
